spring:

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driverClassName: org.h2.Driver
    
    #h2 sql insert data
    data: classpath:data-h2.sql
  
  thymeleaf:
    enabled: true
   