insert into role (id, role) values(0,'ADMIN');
insert into role (id, role) values(1,'MEMBER');
INSERT INTO MEMBER (ID,CREATED_DATE,MODIFIED_DATE,NAME,PASSWORD,PHONE_NUMBER,STUDENT_NUM,ROLE_ID_ID)VALUES(0,NOW(),NOW(),'김동민','a','01027703018','2019631001',0);

INSERT INTO EQUIPSTATE(ID,STATE)VALUES(0,'Activate');
INSERT INTO EQUIPSTATE(ID,STATE)VALUES(1,'Use');
INSERT INTO EQUIPSTATE(ID,STATE)VALUES(2,'Fix');
INSERT INTO EQUIPSTATE(ID,STATE)VALUES(3,'DisEable');
	
INSERT INTO EQUIPMENT(ID,CREATED_DATE,MODIFIED_DATE,EQUIP_NAME,EQUIP_NUM,EQUIP_SEQ_NUM,IS_AVAILABLE,REASON,EQUIP_STATE_ID)
	VALUES(0,NOW(),NOW(),'VR기기','1234','1',true,'',0);